Revert "serial: pl011: Fix DMA ->flush_buffer()"
This reverts commit 8764ed52e2274b9a856d660a7d575bf693f26925 which is
commit f6a196477184b99a31d16366a8e826558aa11f6d upstream.

It's being reverted becuase it causes build errors:

drivers/tty/serial/amba-pl011.c:687:2: error:
  implicit declaration of function ‘dmaengine_terminate_async’;
  did you mean ‘dmaengine_terminate_all’?
    [-Werror=implicit-function-declaration]

Change-Id: I968b66a26997009690fb1f478e225384412f0c01
Signed-off-by: Lee Jones <lee.jones@linaro.org>